### ISSUE TITLE
Glimpse segfaults using the GNOME runtime 3.36

### ISSUE THREAD

**Issue by erikos** [flathub/org.glimpse_editor.Glimpse#2]
We are seeing the following issue with the latest release of Glimpse using the GNOME runtime 3.36

`Mar 18 19:52:26 endless systemd[4750]: Started flatpak-org.glimpse_editor.Glimpse-7002.scope.
Mar 18 19:52:26 endless glimpse-0.1[7014]: Failed to load module "atk-bridge"
Mar 18 19:52:26 endless glimpse-0.1[7014]: Failed to load module "canberra-gtk-module"
Mar 18 19:52:28 endless python2[7042]: Failed to load module "atk-bridge"
Mar 18 19:52:28 endless python2[7042]: Failed to load module "canberra-gtk-module"
Mar 18 19:52:31 endless glimpse-0.1[7014]: g_param_spec_internal: assertion 'is_valid_property_name (name)' failed
Mar 18 19:52:31 endless org.glimpse_editor.Glimpse.desktop[5171]: glimpse-0.1: fatal error: Segmentation fault
Mar 18 19:52:31 endless pagecurl[7105]: pagecurl: gimp_wire_read(): error
Mar 18 19:52:31 endless systemd[4750]: flatpak-org.glimpse_editor.Glimpse-7002.scope: Succeeded.`

**Comment by ghost** [comment]
Sorry about this. It seems someone changed the runtime version in #1 without us having any idea they'd done it. I've reverted it in PR #3, and we're now waiting on the build for that to complete & publish (it'll probably take a couple of hours).

I'm particularly annoyed that whoever did this change ignored the `beta` branch and clearly didn't test anything. We just thought it was an Arch Linux issue when it was first reported to us in the Glimpse project, so this must have been broken for over a week now :man_facepalming: 

cc @bochecha as I want to understand how this was allowed to happen and how we can prevent people making this kind of change in future.

**Comment by ghost** [comment]
Okay, the live version should now be back on platform version 3.34. As you can see from the link above we will work on 3.36 support for the next release (0.1.4)

**Comment by ghost** [comment]
@erikos please let us know when you can if everything works for you on your system after running `flatpak update`. Please note it might take an hour or two after I've posted this for the publish to propagate across the mirrors Flathub normally uses.

**Comment by erikos** [comment]
Thanks Bobby! I just updated to org.glimpse_editor.Glimpse//stable 2020-03-22 17:50:07 and I was able to run Glimpse fine. I will have another QA engineer double check tomorrow as she reported it originally. But looking good on my end. Thanks for the quick follow up!

**Comment by erikos** [comment]
@TrechNex two more positive test results here. So the issue is fixed. Thanks!

**Comment by ghost** [comment]
Excellent! We'll keep this issue open for now as we're continuing to investigate the issue here: https://github.com/glimpse-editor/Glimpse/issues/341

At some point we will need to update Glimpse Image Editor to use GNOME platform 3.36, and it looks like this might not be a Flatpak-specific problem.

**Comment by ghost** [comment]
The fix for this is being built here: https://flathub.org/builds/#/builders/32/builds/17852

Once we've done some final tests it will be published. The version is the same (0.1.2) but we've tagged it as v`0.1.2r2`.

**Comment by ghost** [comment]
Okay, the new version should now be published with support for GNOME platform version 3.36.

@erikos if you can confirm everything is working fine for you then we can close this issue.
