### ISSUE TITLE
Update GNOME runtime to 40

### ISSUE THREAD

**Issue by TrechNex** [flathub/org.glimpse_editor.Glimpse#6]
For anyone that attempts this, there are extra steps you will need to take to make it work. I also encourage you to make use of the beta channel.

Sometimes you can get away with just updating the versions for dependency tarballs that the manifest fetches. If you are unlucky, you will need to backport patches from the GNU Image Manipulation Program source code, and apply those at build time.

Glimpse Image Editor 0.2.0 is based on GNU I.M.P 2.10.18, so if there are GNOME 40 fixes that have been made since then, you will need to apply them.

The app itself is not currently in active development, but it still works just fine. Besides, Flatpaks are sandboxed from the rest of the system anyway. :)

(I'm one of the people that used to work on it, and am one of the "Ghost" users on previous issues & PRs, so if you have questions then let me know)

**Comment by BrainBlasted** [comment]
We probably want 41 now.
